version: 2
jobs:
  build: # the name is misleading, but has to be "build", so it is used outside of workflows
    docker:
      - image: omnetpp/travis-inet:6.0pre9-201029
    parallelism: 4 # make use of all our free containers
    steps:
      - checkout
      - run:
          name: Cloning git submodules
          command: git submodule update --init
      - run: # note: this does not set ALL variables that ". setenv" (in OMNeT++ and in INET) do, but this should to be enough for testing
          name: Setting up environment variables
          command: echo 'export PATH=/root/omnetpp-6.0pre9-linux/bin:$PATH SKIPPED_FEATURES="" SPLIT_INDEX=$CIRCLE_NODE_INDEX SPLIT_TOTAL=$CIRCLE_NODE_TOTAL' >> $BASH_ENV
      - run:
          name: Copying NSC into INET
          command: cp -r /root/nsc-0.5.3 3rdparty
      - run:
          name: Feature tests
          command: ./tests/features/featuretest
      - store_artifacts:
          path: /root/project/tests/features/_log
          destination: log # replace the absolute path above with a shorter one

# the rest is just to schedule a cron job for automated weekly tests,
# and to allow triggering a build manually by pushing a tag
workflows:
  version: 2
  weekly: # this name is arbitrary, but fitting
    jobs:
      - build # the name of the job above
    triggers:
      - schedule:
          cron: "0 16 * * 6" # run on every saturday, at 16:00 UTC
          filters:
            branches:
              only:
                - master
  manual: # this name is arbitrary, but fitting
    jobs:
      - build: # the name of the job above
          filters:
            tags:
              only: trigger-circleci # run if this tag is pushed
            branches:
              ignore: /.*/ # do not run on any branch pushes
