name: Build and tests

on:
  schedule:
      # https://crontab.guru/#0_21_*_*_1-5
    - cron: "0 21 * * 1-5" # "At 21:00 on every day-of-week from Monday through Friday."
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    # nothing

jobs:
  build-native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre9-201029
      - name: Build (native)
        run: |
          docker run -i --env TARGET_PLATFORM=linux --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre9-201029 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/libINET*.so

  build-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["windows", "macosx"]
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre9-201029
      - name: Build (cross)
        run: |
          docker run -i --env TARGET_PLATFORM=${{ matrix.target }} --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre9-201029 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-build.sh

  fingerprints:
    needs: build-native
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre9-201029
      - name: Fingerprint tests
        run: |
          docker run -i --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre9-201029 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-fingerprints.sh

  other-tests:
    needs: build-native
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add debug/release mode when the runtest scripts can switch between
        # MODEs or executables based on command line arguments or envvars
        testdir: ["module", "unit", "packet", "queueing", "protocol",
                  "packetdrill/udp", "packetdrill/tcp", "packetdrill/sctp"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre9-201029
      - name: Run ${{ matrix.testdir }} tests
        run: |
          docker run -i --env MODE=debug --env GITHUB_WORKSPACE --env TESTDIR=${{ matrix.testdir }} \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre9-201029 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-other-tests.sh

