name: "Test: feature"

on:
  schedule:
      # https://crontab.guru/#0_16_*_*_6
    - cron: "0 16 * * 6" # “At 16:00 on Saturday.”
  workflow_dispatch:
    # nothing

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we could go all the way up to 20 even
        split: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        total: [16] # keep these in sync!
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Feature tests (split)
        run: |
          echo "::group::Installing packages"
          sudo apt-get install -y --no-install-recommends git wget curl ca-certificates \
            make ccache clang lld gdb bison flex perl doxygen graphviz libxml2-dev zlib1g-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libz3-dev libopenscenegraph-dev python3
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-omnetpp.sh

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-inet.sh

          echo "::group::Running feature tests"
          SPLIT_N=${{ matrix.total }}
          SPLIT_I=${{ matrix.split }}
          cd $GITHUB_WORKSPACE/inet/tests/features
          # this indirectly calls the script named simply "inet", which handles the MODE envvar internally
          ./featuretest
          echo "::endgroup::"
      - uses: actions/upload-artifact@v3
        if: always() # even if the test failed, of course
        with:
          name: log-${{ matrix.split }}
          path: ${{ github.workspace }}/tests/features/_log
